/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author Dominik
 */
public class Cw2 extends javax.swing.JFrame { 
    
      String kopia;

    public Cw2() {
        initComponents();
        grupa.add(Dodawanie);
        grupa.add(Odejmowanie);
        grupa.add(Mnożenie);
        grupa.add(Dzielenie);

        Dodawanie.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                wynik.setText(Integer.toString(Integer.parseInt(pole1.getText()) + Integer.parseInt(pole2.getText())));

            }
        });


        Odejmowanie.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                wynik.setText(Integer.toString(Integer.parseInt(pole1.getText()) - Integer.parseInt(pole2.getText())));

            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupa = new javax.swing.ButtonGroup();
        Dodawanie = new javax.swing.JRadioButton();
        Odejmowanie = new javax.swing.JRadioButton();
        Mnożenie = new javax.swing.JRadioButton();
        Dzielenie = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        pole1 = new javax.swing.JFormattedTextField();
        pole2 = new javax.swing.JFormattedTextField();
        wynik = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Dodawanie.setText("Dodawanie");
        Dodawanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodawanieActionPerformed(evt);
            }
        });
        Dodawanie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DodawanieKeyTyped(evt);
            }
        });

        Odejmowanie.setText("Odejmowanie");
        Odejmowanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdejmowanieActionPerformed(evt);
            }
        });

        Mnożenie.setText("Mnożenie");
        Mnożenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnożenieActionPerformed(evt);
            }
        });

        Dzielenie.setText("Dzielenie");

        jLabel1.setText("=");

        pole1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));
        pole1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pole1ActionPerformed(evt);
            }
        });
        pole1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pole1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pole1KeyTyped(evt);
            }
        });

        pole2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));

        wynik.setEditable(false);
        wynik.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        wynik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wynikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dodawanie)
                    .addComponent(Mnożenie)
                    .addComponent(Odejmowanie)
                    .addComponent(Dzielenie))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(pole1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pole2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wynik, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pole1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pole2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(wynik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dodawanie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Odejmowanie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mnożenie)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dzielenie)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void DodawanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodawanieActionPerformed
        int w;
        w = Integer.parseInt(pole1.getText()) + Integer.parseInt(pole2.getText());
        wynik.setText(Integer.toString(w));
    }//GEN-LAST:event_DodawanieActionPerformed

    private void OdejmowanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdejmowanieActionPerformed
         
    }//GEN-LAST:event_OdejmowanieActionPerformed

    private void MnożenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnożenieActionPerformed
        
    }//GEN-LAST:event_MnożenieActionPerformed

    private void pole1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pole1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pole1ActionPerformed

    private void wynikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wynikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wynikActionPerformed

    private void DodawanieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DodawanieKeyTyped
        
    }//GEN-LAST:event_DodawanieKeyTyped

    private void pole1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pole1KeyTyped
        
    }//GEN-LAST:event_pole1KeyTyped

    private void pole1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pole1KeyReleased
        if (Dodawanie.isSelected()) {
            wynik.setText(Integer.toString(Integer.parseInt(pole1.getText()) + Integer.parseInt(pole2.getText())));
        }
    }//GEN-LAST:event_pole1KeyReleased
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cw2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cw2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cw2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cw2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                
                new Cw2().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Dodawanie;
    private javax.swing.JRadioButton Dzielenie;
    private javax.swing.JRadioButton Mnożenie;
    private javax.swing.JRadioButton Odejmowanie;
    private javax.swing.ButtonGroup grupa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField pole1;
    private javax.swing.JFormattedTextField pole2;
    private javax.swing.JFormattedTextField wynik;
    // End of variables declaration//GEN-END:variables
}

